apiVersion: batch/v1
kind: Job # Deployment will automatically restart when killed. Use Pod if not needed
metadata:
  labels:
    k8s-app: research
  name: abhibha-images2-34-36
  namespace: ecepxie
spec:
  template:
    metadata:
      labels:
        k8s-app: research
    spec:
      restartPolicy: Never
      containers:
      - name: research
        image: gitlab-registry.nrp-nautilus.io/prp/jupyter-stack/prp
        imagePullPolicy: Always
        workingDir: /abhibha-volume/Image-Enhancer/
        command: ["python","dhe.py"]
        resources:
          requests:
            memory: "2Gi"
            cpu: "1"
            nvidia.com/gpu: 0
          limits:
            memory: "4Gi"
            cpu: "1"
            nvidia.com/gpu: 0
        volumeMounts:
        - mountPath: /abhibha-volume
          name: abhibha-volume
      volumes:
        - name: abhibha-volume
          persistentVolumeClaim:
            claimName: abhibha-volume
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: gpu-type
                operator: In # Use NotIn for other types
                values:
                - 1080Ti
